import { Metadata } from "next";
import RootLayout from './layout';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ServerRootLayout({ children }) {
  return (
    <RootLayout>
      {children}
    </RootLayout>
  );
}